name: Automation_localcommit_scala
description: test random description
version: 1.0.0
author: abhisheks+e2etests@prophecy.io
language: scala
buildSystem: ''
buildSystemDetails:
  artefactID: automationlocalcommitscala
  parentArtefactID: abhishekse2etestsprophecyioteam
  buildSystem: maven
  author: null
  createdAt: '2025-10-31 05:02:08'
pipelines:
  pipelines/Automation_localcommit_scala_Pipeline:
    name: Automation_localcommit_scala_Pipeline
    description: automation workflow
    author: abhisheks+e2etests@prophecy.io
    mode: batch
    artefactID: ''
    language: scala
    createdAt: '2025-10-31 05:04:39'
    datasets:
      inputs:
      - datasets/test_dataset
      outputs: []
    subgraphs: []
    dependencies: {}
datasets:
  datasets/test_dataset:
    name: test_dataset
    description: ''
    author: abhisheks+e2etests@prophecy.io
    createdAt: '2025-10-31 05:11:39'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 3
        datasetType: File
        description: ''
        author: abhisheks+e2etests@prophecy.io
        createdAt: '2025-10-31 05:11:39'
templates: {}
jobs: {}
gemContainer:
  languageVersion: 2.12.15
  gemLibsVersion: 1.1.26
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2025-10-31 05:02:08'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2025-10-31T05:03:02.426Z'
  name: ProphecyLibsScala
  version: 8.14.0-SNAPSHOT
  createdAt: '2025-10-31T05:02:08.55999Z'
  type: plibMaven
  enabled: true
  entity: Project
  description: Default dependency for Prophecy Libs
  scope: Project
  exclusions: []
  editable: true
projectDependencies:
  '1':
    projectUID: 1
    projectName: ProphecySparkBasicsScala
    repositoryPath: gitUri=http://gitserver:3000/oimECIpO_team_2/oimECIpO_project_1.git&subPath=
    version: 0.2.6.3
    isDefault: true
    author: null
    createdAt: '2025-10-31 05:01:40'
  '2':
    projectUID: 2
    projectName: ProphecyWarehouseScala
    repositoryPath: gitUri=http://gitserver:3000/oimECIpO_team_2/oimECIpO_project_2.git&subPath=
    version: 0.0.6
    isDefault: true
    author: null
    createdAt: '2025-10-31 05:01:40'
  '14262':
    projectUID: 14262
    projectName: scala_project
    repositoryPath: gitUri=http://gitserver:3000/y26UTxfT_team_5/CRHsPoxm_project_14262.git&subPath=
    version: scala_project/v4.0.0.0
    isDefault: false
    author: null
    createdAt: '2025-10-31 05:01:40'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
projectConfigurations: {}
